### PR TITLE
Notify callback support

### LINKED ISSUE #25: Support Notify in C_OpenSession
Support 4th and 5th arguments of C_OpenSession via a callable argument.

### PR DESCRIPTION
**Pull request by gamringer**

### CODE REVIEW

**Comment by gamringer** [comment]
Unfortunately, SoftHSM doesn't support those notify events, so I tested by faking it in $session->login()

**Comment by gamringer** [comment]
pApplication and notify need to be nullable. As of now, it works when they're supplied, but not when not.

**Review by vjardin — CHANGES_REQUESTED** [review]
Minor review : let's the callback be static here.

**Comment by gamringer** [comment]
After discussing with OASIS people at recent ICMC, it turns out that literally no manufacturer implemented this. Closing this for now.

**Comment by vjardin** [comment]
> After discussing with OASIS people at recent ICMC, it turns out that literally no manufacturer implemented this. Closing this for now.

Just in case, do they have a test framework for self certification? It is nice that you have some contacts with them.

**Pull request closed without merging**
