### PR TITLE
Numeric & boolean attributes are now returned in those types instead of strings

### LINKED ISSUE #63: Variable types of attributes are not compareable with constants
To be able to control an instance of `\Pkcs11\Key` we need to get some attributes from it:

```
$attributes = $privateKey->getAttributeValue([
    \Pkcs11\CKA_PRIVATE, 
    \Pkcs11\CKA_SIGN, 
    \Pkcs11\CKA_KEY_TYPE
]);
```

All of these values are raw bytestrings and it is impossible to compare them with the existing constants. E.g.:

```
if ($attributes[\Pkcs11\CKA_KEY_TYPE] === \Pkcs11\CKK_RSA) {
   ...
}
```
But as the attributes are strings this does not work. Is this an intended behavior or are we missing something?

It is possible to use integer or boolean values when e.g. creating key pairs using the same key constants:

```
$keypair = $session->generateKeyPair(new Pkcs11\Mechanism(Pkcs11\CKM_RSA_PKCS_KEY_PAIR_GEN), [
	Pkcs11\CKA_VERIFY => true,
	Pkcs11\CKA_MODULUS_BITS => 2048,
	Pkcs11\CKA_PUBLIC_EXPONENT => hex2bin('010001'),
	Pkcs11\CKA_LABEL => "Test RSA Public",
],[
	Pkcs11\CKA_TOKEN => false,
	Pkcs11\CKA_PRIVATE => true,
	Pkcs11\CKA_SENSITIVE => true,
	Pkcs11\CKA_SIGN => true,
	Pkcs11\CKA_LABEL => "Test RSA Private",
]);
```

Wouldn't it be correct, if these values are also boolean and/or integer values, when they are received back?

If this is an internal issue of how PKCS11 works under the hood, can you share some best practice how to compare these values?

Would this be a correct comparison:

```
if ($attributes[\Pkcs11\CKA_KEY_TYPE] === pack("P", \Pkcs11\CKK_RSA)) {
   ...
}
```

?

Thanks!

### PR DESCRIPTION
**Pull request by gamringer**
@JanSlabon This closes #63 

@vjardin your input is always welcome, as usual

### CODE REVIEW

**Comment by vjardin** [comment]
LGTM.

Any options in order to avoid such list and having pkcs11 libraries doing the if()s ?
I do 'ot think so neither, just in case.... since it'll be painful to maintain.

**Comment by JimmyHamel** [comment]
LGTM.

**Comment by gamringer** [comment]
@vjardin There is no such way that I know. As for the pain of maintaining it, given that OASIS is very slow at releasing new versions of the spec, I don't think this will be such a bother.

It may only be a bother for vendor-specific attributes, which will always be returned as strings Unless of course, we make those lists somehow configurable in php.ini, or simply allow to add new attributes with their type in php.ini.

**Comment by vjardin** [comment]
So if any vendors need an extension, they'll be welcomed to contribute :-)

**Comment by gamringer** [comment]
Agreed

I already included some definitions for Yubikeys since they're publicly documented (61dae08) but I'll accept PRs from any vendor.

**Pull request merged**
