### PR TITLE
CI GitHub

### PR DESCRIPTION
**Pull request by vjardin**
It is a first round for CI based on the new GitHub Workflow/Action framework.

### CODE REVIEW

**Comment by vjardin** [comment]
An example is available [here](https://github.com/vjardin/php-pkcs11/runs/1634218587?check_suite_focus=true)

**Comment by gamringer** [comment]
We should probably have separate jobs for testing with both PHP 7.4 and 8.0 and install explicit versions of PHP
`sudo apt-get install php7.4-cli php7.4-dev`
and later:
`phpize7.4`
`./configure --with-php-config=/usr/bin/php-config7.4`
and then:
`sudo apt-get install php8.0-cli php8.0-dev`
and later:
`phpize8.0`
`./configure --with-php-config=/usr/bin/php-config8.0`

Also, in order to run tests with all available mechanisms, we should use softhsm2 v2.6 from the source instead of 2.2 from the package repository.

**Comment by vjardin** [comment]
I would prefer to create some additionnals jobs for such cases. For "legacy" users we can rely on the upstream packages while we can have some additional tests using the lastest sources.

Using github, we can have a matrix of test to be run with many PHP versions. I plan to send an update with many versions but first I'd like to get a v0 for the CI integrated with github and then later I'll provide such updates.

**Comment by vjardin** [comment]
Thanks, it will be used as a foundation for more tests with more PHP releases and a specific set with the latest support from SoftHSM2.

**Pull request merged**
